# Generated by Django 2.2.3 on 2019-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('disease', models.TextField()),
                ('previousHistory', models.TextField()),
                ('doctor', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
