# Generated by Django 2.2.3 on 2019-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_auto_20191128_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
    ]
