# Generated by Django 2.2.3 on 2019-12-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(default='none', max_length=254)),
                ('phone', models.BigIntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('specialization', models.TextField(max_length=500)),
                ('on_duty', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
